schema_version = "1.0.0"

id = "braindead_blender"
version = "1.0.0"
name = "BrainDead Blender Tools"
tagline = "Mesh processing and character pipeline tools by BiloxiStudios Inc"
maintainer = "BiloxiStudios Inc <contact@biloxistudios.com>"
type = "add-on"

tags = ["Mesh", "Import-Export", "Game Engine", "Pipeline"]

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

website = "https://github.com/BizaNator/BrainDeadBlender"

copyright = [
    "2024-2025 BiloxiStudios Inc",
]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    ".*",
    "*.zip",
    "*.pyc",
    "*_Log.txt",
]
